# MacGuardian Watchdog Theme for Powerlevel10k
# Omega Technologies - Dark Cyberpunk Aesthetic
# Add to ~/.p10k.zsh or source in your .zshrc

# Color definitions
typeset -g POWERLEVEL9K_MACGUARDIAN_PURPLE='#8A2BE2'  # Electric purple
typeset -g POWERLEVEL9K_MACGUARDIAN_RED='#FF0044'     # Neon red
typeset -g POWERLEVEL9K_MACGUARDIAN_CYAN='#00FFFF'    # Cyan glow
typeset -g POWERLEVEL9K_MACGUARDIAN_GRAY='#808080'    # Dim gray

# Prompt elements
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    time
    user
    dir
    vcs
    newline
    prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
)

# Time
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_TIME_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_PURPLE
typeset -g POWERLEVEL9K_TIME_BACKGROUND=''
typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''

# User
typeset -g POWERLEVEL9K_USER_DEFAULT_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_PURPLE
typeset -g POWERLEVEL9K_USER_DEFAULT_BACKGROUND=''
typeset -g POWERLEVEL9K_USER_ROOT_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_RED
typeset -g POWERLEVEL9K_USER_TEMPLATE='%n'
typeset -g POWERLEVEL9K_USER_ICON=''

# Directory
typeset -g POWERLEVEL9K_DIR_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_GRAY
typeset -g POWERLEVEL9K_DIR_BACKGROUND=''
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=''
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_CYAN
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_PURPLE
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

# VCS (Git)
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
typeset -g POWERLEVEL9K_VCS_GIT_ICON=''
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_CYAN
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_RED
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_RED
typeset -g POWERLEVEL9K_VCS_BACKGROUND=''
typeset -g POWERLEVEL9K_VCS_BRANCH_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_PURPLE
typeset -g POWERLEVEL9K_VCS_STAGED_ICON='●'
typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='●'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='●'
typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'

# Status
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_CYAN
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_RED
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=''
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=''

# Command Execution Time
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_PURPLE
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=''
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2

# Background Jobs
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_PURPLE
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=''
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

# Prompt Character
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_RED
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$POWERLEVEL9K_MACGUARDIAN_RED
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='>'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='<'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='>'
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

# Transient prompt (when you press enter)
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Separators
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '

# Show header on startup
if [[ -z "$MACGUARDIAN_HEADER_SHOWN" ]]; then
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                                                            ║"
    echo "║    Ω-Technologies // MacGuardian Watchdog                 ║"
    echo "║                                                            ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    export MACGUARDIAN_HEADER_SHOWN=1
fi

